anacrolix/torrent

- magnet.go
- magnet_test.go
Tests for `func ParseMagnetURI(uri string) (m Magnet, err error)`.
Also, cleaned up some minor details in `ParseMagnetURI` implementation for readability and added a doc string
> Add tests for ParseMagnetURI

- dht/announce.go
- dht/dht.go
This is beneficial to users who are running their own private DHT servers or have outbound connections to port 6881 disallowed on firewalls.
> Added BootstrapNodes to dht.ServerConfig

- metainfo/_testdata/trackerless.torrent
- metainfo/builder.go
- metainfo/metainfo.go
- metainfo/metainfo_test.go
Based on the official spec
(http://www.bittorrent.org/beps/bep_0005.html) trackerless metainfo
files do not contain announce key. Instead nodes key has to be
specified. This PR adds support for nodes key into metainfo package. It
also contains a test metainfo file.
> Added support for trackerless metainfo files

- cmd/torrent-create/main.go
- cmd/torrent-verify/main.go
- dht/dht.go
- mmap_span/span.go
```torrent-create``` and ```torrent-verify``` did not work correctly when a single file is present in ```metainfo``` torrent file. ```torrent-create``` now correctly fails if the path passed as an command line argument does not exist - otherwise it throws runtime panic as the non-existent file case is not handled by it. ```torrent-verify``` now has a summary flag. Finally, in ```span.go``` I've cheekily sneaked in a change which defines the ```span``` type more like idiomatic Go (I have a weird OCD :-)).
> Multiple file metainfo mode support in cmd tools

- client.go
The announce attribute was ignored while creating spec from metaInfo. Because of that torrents without announceList weren't announced to the tracker, rendering them useless.
> fix: added announce to torrent spec

- client.go
when I disable TCP or UDP and  assign listen address  `x.x.x.x:0`, that means I want to use dynamic port to bind, then `listenedAddr` is not the real address. Anyway I think is a good choice to using `Addr().String()` for get bind real address.
> fix listenedAddr  bug when TCP or UDP bind dynamic port

- dht/announce.go
A missing condition leaves the default root servers to be added even if `NoDefaultBootstrap` is `true` and no custom bootstrap servers are specified.
This pull request adds the missing check.
> fix disabling of global bootstrap servers

- cmd/torrentfs/main.go
> torrentfs: fix panic when testPeer is not specified

- fs/torrentfs.go
- fs/torrentfs_test.go
I return false if parent="" and child="" only to satisfy the test (not sure when this happens). Otherwise I would have made it `if len(parent) == 0 { return true }`
Fixes #104
> fs: fix isSubPath for top-level directories

- metainfo/info.go
removes the print of (path, err) in function BuildFromFilePath
> feat: remove print BuildFromFilePath

- metainfo/info.go
Allow setting source in torrents (see https://github.com/Rudde/mktorrent/commit/905ccc2273a96ff0b6c774a67798a83af8cb334b).
> Added optional source flag to torrent files

- cmd/torrent-verify/main.go
Per #140, I've updated the patch (such as it is) to work with the rewrite.
> Abort verify at first hash mismatch.

- client.go
- storage/file.go
- torrent_test.go
`TorrentSpec.Storage` was not honored when calling `Client.AddTorrentSpec`
and the configured `cfg.DefaultStorage` was always used. Now if you construct
your `TorrentSpec` you can specify any `StorageImpl`
Also, the most common use case for custom storage being per-torrent paths for
FileStorage, this adds a `pathMaker` function to the File implementation that
allows customization, along with the default (always use base path) and my use
case (which seemed common enough from the Gitter chat) which is infohash based
subdirectories.
All Public methods have not changed signature, but 1 private method did, hence
the test update.
> fix `Spec.Storage` and allow per-torrent dir

- torrent.go
- torrent_stats.go
I'd need access to peer counts, so I added 4 new methods on the Torrent struct to provide them.
`NumActivePeers`
`NumHalfOpenPeers`
`NumPendingPeers`
`NumTotalPeers`
The first three are straightforward and return the length of the underlying map (`t.conns`, `t.halfOpen`, and `t.peers`, respectively)
`NumTotalPeers` builds a map containing the set of all peer addresses and returns the length of that map, thus ensuring peers present in multiple maps aren't double counted.
> Add public methods for torrent peer counts

- reader.go
- t.go
Added few helper functions. 
1) t.PieceBytesMissing - as you've said, probably, no need to alter PieceState with this information calculation all over, so just adding straight call to torrent.
2) r.CurrentPos - this one is useful for custom readers/storage creation.
3) r.SetNonResponsive - there is a responsive setter, but no way back.
> added few helper functions

- torrent.go
We need to broadcast an event when a torrent is closed, as other goroutines(such as the torrent `Reader`) maybe waiting for this.
> signal an event when torrent closed

- client.go
If DHT is diabled, `Client.dht` will be nil, and the invoking of `AddDHTNodes` will cause a `nil pointer` panic. maybe we can do nothing in `AddDHTNodes` if DHT is disabled.
> Do not add nodes if dht is disabled

- storage/mmap.go
The `ih` field must be initialized when a new `mmapStoragePiece` created, otherwise the `pieceKey` method doesn't work as expected.
> bug fix: initial infoHash for mmapStoragePiece

- tracker/http.go
Mainly follows https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779
but also disables HTTPS certificate verification.
> Provide trackers specific http client

- utp_go.go
- utp_libutp.go
allow disable_libutp flag usage for build, in case cgo is used and you don't want to use libutp.
> added disable_libutp build flag usage

- cmd/tracker-announce/main.go
- config.go
- tracker/http.go
- tracker/http_test.go
- tracker/tracker.go
- tracker/tracker_test.go
- tracker/udp_test.go
- tracker_scraper.go
Currently library is not setting User-Agent for HTTP requests, so by default it's 'Go-http-client/1.1' and that causes problems with trackers that have Whitelist settings.
Change allows to change default UserAgent to anything.
> adding http user-agent setters and usage

- client.go
- config.go
- socket.go
Here is a very dumb implementation of using proxy in the library.
We need to use it with the HTTPClient (which is pretty common case and has support in the transport), and within Dialing for outgoing connection.
I have tested it with socks5 proxy on a wireless connection which is blocking trackers requests and outgoing torrent requests and got it working.
We would not be able to seed, probably, but at least we can download.
> Proxy support in the library

- portfwd.go
Moving upnp from syncthing repository to local to minimize prerequisites and C headers usage.
> migrating upnp from syncthing

- client.go
- config.go
- tracker/http.go
- tracker/tracker.go
- tracker_scraper.go
Trying to revert usage of proxies for HTTP requests.
I remember you did not want to use this way, but I don't see any good approach with less actions to do.
The change will add HTTPProxy, which can differ from listener's proxy, if needed. 
Tried on my environment, looks fine, all connections are made to the proxy.
> reverting usage of proxy for http requests

- fs/torrentfs.go
* Fix a bug where `ENOENT` is returned when the node for an entry in the root directory of a torrent is requested.  The problem was that the full pathname to each entry in that directory would wrongly get prefixed with a slash, which means that all comparisons against the pathnames of `(*torrent).File` objects would fail as the latter are always relative.
* Fix a bug where the basenames of files are extracted incorrectly when listing the entries in a directory.  The problem was that the `dirNode.path` string was treated as a list of path components when in fact it's just a pathname string.
> torrentfs: some pathname-related fixes

- torrent.go
- tracker_scraper.go
Some trackers (chihaya, https://bit.ly/2KdOu2G) require the "Stopped" event to be sent, so the seeder can be removed from the swarm. This patch adds the "Started" and "Stopped" events.
> Adding Started and Stopped events

- tracker/http.go
- tracker/peer.go
The method `fromDictInterface` was not exported from the `Peer` structure.
People using this `Peer` struct from outside the library would be happy to access the method to instantiate peers from a non-compact format.
This method is a constructor in some way, it should be exported to provide users a convenient way to instantiate a peers from a map without having to rewrite the same logic
> Export Peer function

- tracker/http.go
- tracker/http_test.go
Hi,
Since the `HttpResponse` that resides in tracker/http.go is a well known structure i'd like to have it exported. This structs is already tagged with bencode and is easily reusable, more than and than it's well tested. I feel like it should be exported to be use-able in other projects.
How do you feel about that?
> Anthonyraymond export well known

- file.go
It would be good to have some method for getting the BytesCompleted per file.
This is a possible solution for that. We could probably add a check to ensure bytesLeft is never greater than the file length.
> Add BytesCompleted method for files

- metainfo/fileinfo.go
- t.go
non-Latin letters in the file names will appear garbled. To solve this problem, some programs write the utf-8 name in the field path.utf-8 and write the field path in some other encoding.
> use path.utf8 first for some torrent

- config.go
- portfwd.go
New config option that one can set to change UpnP ID, which is listed as service name in routers etc. It's still anacrolix/torrent by default.
> Possibility to change UpnP ID

- peerconn.go
- pexconn.go
Prevent further write attempts if the write buffer is full. Extends #353.
> PEX: integrate with send throttling

- cmd/torrent/main.go
Allow testing in different IP stack combinations.
> cmd/torrent: add -ipv4/-ipv6 options

- metainfo/fileinfo.go
- metainfo/info.go
- metainfo/metainfo.go
Add respective BEP numbers to the comments for each of the metadata fields. This should help finding information on the format and appropriate use.
Those fields which I couldn't find in a BEP are left out.
> add BEP references to documentation of metadata fields

- cmd/torrent-metainfo-pprint/main.go
Helps to confirm custom addresses.
> torrent-metainfo-pprint: include the 'nodes' field into the output when non-empty

- client.go
- spec.go
- torrent.go
For https://github.com/anacrolix/torrent/pull/408#issuecomment-637211537
I wasn't 1000% sure about whether setting the torrent properties belonged in `MergeSpec`, but it seemed to follow the existing functionality.
Thanks!
> Add DisallowDataDownload/Upload to TorrentSpec and small log cleanup

- webtorrent/tracker_client.go
On socket reconnect, reannounce any webrtc offers that might have been half-open before the webtorrent
socket disconnected. This implementation closes any existing half-open offers and republishes them,
but does nothing to existing webrtc connections which are still running (these are cleaned up
elsewhere and are not owned by this code)
See #416 for additional details.
> Reannounce webtorrent webrtc offers on reconnect

- webtorrent/tracker_protocol.go
Adding "omitempty" to json marshalling, bringing the webtorrent tracker AnnounceRequest in line
with BEP-3, which states omitting the the "event" field is acceptable.
Fixes half of: https://github.com/anacrolix/torrent/issues/416
> Align webtorrent tracker to BEP-3

- pex.go
- pexconn.go
Tracker-less PEX-only swarms quickly turn fully meshed (every peer has a connection to every other peer), contrary to tracker-backed swarms which have periodic poll interval for contacting trackers.  Proposed  is to mimic the throttling of peering info supply by adding a  minute-long cool down period (which  coincides with  the shortest  tracker announce interval) during which incoming PEX messages are discarded without processing.
Thoughts and comments are welcome, @anacrolix
> PEX: impede full-meching in tracker-less swarms by adding a cooldown minute

- storage/file.go
We cannot close underlying Boltdb PieceCompletion if it is not closable.
> Change ClientImpl to ClientImplCloser

- storage/bolt-piece-completion.go
- storage/bolt-piece.go
- storage/bolt.go
- storage/default-dir-piece-completion-boltdb.go
- storage/default-dir-piece-completion-sqlite.go
- storage/sqlite-piece-completion.go
This adds 2 buildtags. `noboltdb` doesn't build boltdb and `nosqlite` doesn't build sqlite3 . This helps in decreasing size of binaries.
> Added build tags to disable few packages if necessary

- t.go
Just a heads up: using `range` and/or `defer` prevents function inlining. This is fine for infrequently called functions and/or large functions, but for simple public methods like these, I'd assume it's better for them to be inlined.
Also worth mentioning that `pieceStateRuns()` can't be inlined atm, so allowing for `PieceStateRuns()` to be inlined makes sense.
> PieceStateRuns: reduce copying and make inlineable

- client.go
A bit too much functional programming, lol.
Don't get me wrong, I'm a fan of functional programming myself. But Go isn't a functional language, and it just adds too much overhead since Go's compiler isn't that smart. Plus there's basically no immutability in the language, which IMO is pretty important for real functional programming. I'll also mention that Go only just reached the point where functions with closures are inline-able -- with the release of Go 1.17.
Take a look at the best comment of this reddit post: https://www.reddit.com/r/golang/comments/nlh1kj/the_future_of_functional_programming_in_go_118/gziryo3/
If this project were written in Rust -- functional programming would work. Doesn't even matter that Rust isn't a functional language.
That being said, `eachDhtServer` and …
> Simplify haveDhtServers()

- client.go
Made `BadPeerIPs` inlineable since I changed `badPeerIPsLocked` anyway. Also eliminated an extra torrentsAsSlice copy since Go wasn't smart enough to figure it out.
> Drop xerrors and missinggo/slices dependency for Client

- peerconn.go
- torrent.go
Basically bind the lifetime of chunkPool to the torrent by using `sync.Pool` in lieu of `*sync.Pool`. Gives the GC ever so slightly less work to do.
> Clarify ownership of (*Torrent).chunkPool

- metainfo/nodes.go
Not a big deal, but there isn't a need to allocate an object to check that `*Node` satisfies `bencode.Unmarshaler`.
> Avoid allocating memory when checking interface

- tracker/http/http.go
- tracker/http/http_test.go
Fixes https://github.com/anacrolix/torrent/issues/534.
> Fix http announce of infohash containing ' ' bytes

- reader.go
Reorder some of the fields to reduce the size of `reader`. Not much of a change -- original size was 104 bytes, with changes (moving bool's to the end) the size is 96 bytes. There's also the whole cache-friendly bit -- I tried reordering fields to help here, but I doubt it makes much of a difference.
Some other notes: `sync.Locker` is a 16 byte field. I suggest changing this to something like `*sync.RWMutex` or `*lockWithDeferreds`. This would not only reduce size but would allow access to `RLock`/`RUnlock`.
`pieceRange` could also be shrunk to 8 bytes, but I feel like I'm probably asking for too much lol.
> Reorder fields to reduce padding in reader

- client.go
- t.go
- torrent.go
Data races shouldn't be an issue since `missinggo.Event` didn't originally use a lock anyway. As far as I can tell `missinggo.Event` simply provides insurance that the channel isn't closed more than once. If we are careful about keeping the channel initialized on the construction of the torrent, as well as making sure to re-`make` the `gotMetainfo` channel when setting `.info = nil`, then the double close issue shouldn't be encountered.
> Simplify (*Torrent).gotMetainfo

- reader.go
Couldn't find an elegant way to early exit on bad whence. Using a closure could reduce code duplication slightly, but it's overkill for only 3 cases.
Note that returning 0 on an invalid whence is the behavior of `strings.Reader` and `bytes.Reader`.
> Inlineable reader.Seek and no-lock return for bad whence

- bencode/bench_test.go
- client_test.go
- cmd/torrent-metainfo-pprint/main.go
- cmd/torrent-verify/main.go
- iplist/iplist_test.go
- misc_test.go
- mse/mse_test.go
- peer_protocol/decoder_test.go
- peerconn.go
- peerconn_test.go
- request-strategy/order_test.go
- rlreader_test.go
- storage/test/bench-piece-mark-complete.go
- torrent.go
- torrent_test.go
`range iter.N` looks nice and doesn't allocate, but unfortunately using a `range` expression blocks a function from being inlined wherever it's used (for now). It's not that we need inlining in all cases, but I do think a C-style for loop looks just as nice and is probably clearer to the majority. There also aren't any clear disadvantages to changing (unless you just happen to dislike the look of C)
> Drop bradfitz/iter dependency

- reader.go
Small fixes that prevent inlining of public functions
> Inlineable (*reader).SetReadAhead and (*reader).Close

- file.go
Also renamed `bytesCompleted` to `bytesCompletedLocked` for a bit of self documentation. If this is a problem I'll change it back, but it doesn't seem like the function is used anywhere besides here anyway.
> Inlineable `(*File).BytesCompleted()`

- global.go
- torrent.go
Not saying that https://github.com/arvidn/libtorrent has all the answers, but I think it's a good reference: https://github.com/arvidn/libtorrent/blob/95afba30e9acfd8411076a0b05f7ca69bf33b9bb/src/ut_metadata.cpp#L145-L151.
They use `4 * 1024 * 1024`, but we can double that to be safe. Note how they also use a multiple of 16*1024. I found another torrent client that used `2 * 1024 * 1024`, so we are on the high end regardless.
---
Had a nice chuckle at the comment next to 10MB.
Fixed a redundant check and future possible clash with `bytes` package name.
> Clarify maximum value of "metadata_size"

- client.go
- client_test.go
- peerconn_test.go
- pexconn_test.go
Allow for certain values to always be properly initialized on construction -- namely the maps for now. I'm currently working on a change that requires a baseline constructor; this change would make the use of `chansync.BroadcastCond` and `chansync.SetOnce` obsolete -- i.e. one can have channel members without worrying about proper initialization/destruction of a `chan struct{}`.
As for why `makeClient` returns a value instead of a pointer: returning a value gives us more options -- you can always take a pointer from a value later on cheaply, and have things moved to the heap if they weren't already. The same can't be said about getting a value back from a pointer. GC also could potentially have less work to do. Plus I personally find ownership to be an important concept (semi-borrowed …
> Create default constructor for Client

- t.go
Changed doc to note that `SetDisplayName()` doesn't clobber `.displayName` if metainfo is available. Should this function be changed so that it always clobbers?
> Inlineable `(*Torrent).SetDisplayName()`

- metainfo/piece.go
`copy`  will copy exactly `HashSize` bytes here.
> metainfo: Remove reflection dependency for `Piece.Hash()`

- bencode/decode.go
Preserve as much type as possible (I know -- it'll be converted to an `interface{}` anyway). We can return `[]interface{}` here instead of `{}interface`.
> bencode: Simplify `(*Decoder).parseListInterface()`

- bencode/encode.go
Nope, it doesn't really matter. But anyway, see https://github.com/golang/crypto/blob/c084706c2272f3d44b722e988e70d4a58e60e7f4/cryptobyte/asn1.go#L267
> bencode: get type of `big.Int` without creating instance

- torrent.go
Honestly a name like `BytesLeft` would have been more suitable, but it's too late for that I guess.
> Inlineable `(*Torrent).BytesMissing()`

- bencode/fuzz_test.go
- client-nowasm_test.go
- config.go
- iplist/packed.go
- issue211_test.go
- metainfo/fuzz_test.go
- peer_protocol/fuzz_test.go
- storage/bolt-piece-completion.go
- storage/bolt-piece.go
- storage/bolt.go
- storage/default-dir-piece-completion-sqlite.go
- storage/mmap.go
- storage/sqlite-piece-completion.go
- storage/sqlite/direct.go
- storage/sqlite/sqlite-storage_test.go
- torrent.go
- torrent_mmap_test.go
- tracker_scraper.go
- utp_libutp.go
Allows tracker_scraper to have a custom function to do DNS lookups. This allows things like dns-over-https.
I also reverted `// +build` build tags along with every `// go:build` line to support Go 1.16.
- for Go 1.17, it can handle both
- for Go 1.16, it **must** have both, else you'll get an error while building:
peer-store.go:5:2: //go:build comment without // +build comment
- You can repro this by downgrading Go to 1.16 and just running `go build ./...` on anacrolix/torrent's [current master](https://github.com/afjoseph/torrent/commit/8b368b3832ca87f19c703ab48ba355e625190b2b) without the changes in this PR
- For my use case, I can't update to Go 1.17 yet since [some projects](https://issueexplorer.com/issue/filecoin-project/lily/679) downright panic when upgrading
@anacrolix lemme know …
> [trackerscraper] Add custom DNS lookup function

- peerconn.go
- peerconn_test.go
- pex.go
- pex_test.go
- pexconn.go
As discussed under #691 this implements the "_linked list_" approach:
> 2. replace t.ev slice with a linked list and track the "seen" events using pointers, relying on GC to reclaim the memory.
This is a complete implementation. Integration testing conducted in a docker-backed tracker-less swarm with 1 seeder and 50 downloaders with seeding on.
This also includes reworked the unit tests for less exposure to the internal details.
The unidirectional linked list is a bit unusual: we don't hold an explicit reference for its head, only for the tail. This means  that while the many Conn's are catching up on the events and advance their references, the preceding entries become inaccessible and, therefore, should qualify for garbage collection – that's the main idea here. This is why the list …
> PEX: fluid event log

- go.mod
- go.sum
- pex.go
Drop local functions used to implement search on NodeAddr lists in favour of using the methods added under anacrolix/dht#53.
> PEX: use new NodeAddr search methods in krpc

- go.mod
- go.sum
- pex.go
anacrolix/dht#54 fixes the marshaller — the workaround can be removed.
> PEX: remove workaround for krpc marshaller

- client.go
- webtorrent/tracker_client.go
- wstracker.go
I have a VPN provider that has audit rules for BitTorrent download. Setting `clientConfig.HTTPProxy` to nil works for UDP/HTTP trackers, but websocket trackers still use my environment variable and go through my VPN network.
> Set proxy of websocket tracker

- tracker/http/http.go
Some http private tracker requires the original URL querystring (contains a unique user key) to be in the first position. this is not following the HTTP protocol but understandable for anti-DDOS purposes.
The original logic is to add other arguments to the Query object, then re-encoded to be the query string, this cause the key position changed.
This PR make sure that the original query param kept in the original position if appears.
> http trackers query string kept at original positon

- client_test.go
- fs/torrentfs_test.go
- issue97_test.go
- metainfo/metainfo_test.go
- storage/bolt-piece-completion_test.go
- storage/file_test.go
- storage/issue95_test.go
- storage/issue96_test.go
- test/transfer_test.go
- util/dirwatch/dirwatch_test.go
We can write less code by using the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
> test: use `T.TempDir` to create temporary test directory

- client.go
- client_test.go
- go.mod
- go.sum
- network_test.go
- socket.go
- utp_go.go
- utp_libutp.go
- utp_test.go
I'm opening this as a draft for now, because I'm not certain I like the use of `utp.NewSocketOpt` all the way up the chain in `listenAll`.
I'd love your input, @anacrolix, but I was thinking of perhaps defining a `socket` interface in addition to the `utpSocket` interface in `utp.go`, and then a `socketOpt` type which could be used for configuring sockets more generally.
Closes #676.
> Pass client logger to anacrolix/go-libutp sockets

- request-strategy-impls.go
- request-strategy/order.go
- request-strategy/torrent.go
The calculation of whether we should ignore a piece in GetRequestablePieces ends up doing an allocation for every piece, when
all we really need to do is query the index in the torrent. Provide an IgnorePiece function instead, which avoids the need for a temporary allocation.
Observed to cut out 40% of object allocations in some workloads (large download, lots of seeds).
(I'm not clear why Go doesn't optimise this onto the stack, as it doesn't seem to escape, but it was turning up as an extremely hot allocation path in pprof flame graphs.)
> Avoid heap allocation in GetRequestablePieces

- .github/workflows/go.yml
- webtorrent/setting-engine.go
- webtorrent/setting-engine_js.go
- webtorrent/transport.go
Problem:
- Now user can see logs like: `mux ERROR: 2022/04/09 13:41:02 mux: ending readLoop dispatch error io: read/write on closed pipe` (when restart the app), but can't do anything with this logs (filter/format).
Probably it's bad solution (to discard logs), but It's unclear for me - how to integrate pion logger with anacrolix logger: 
- api *webrtc.API - is the global variable initialized way before i creating configuration of anacrolix
> Discard webrtc logs

- go.mod
- go.sum
Errors are like: https://github.com/edsrzf/mmap-go/issues/22
> Update mmap-go dep because of errors on Windows

- go.mod
- go.sum
- request-strategy/tidwall-btree.go
[Mabel](https://github.com/smmr-software/mabel) does not compile after running `go get -u .` due to breaking changes in the `tidwall/btree` package, a dependency of this project.
This PR pulls in the latest changes to `tidwall/btree`.
> Update tidwall/btree (0.7.2 -> 1.3.1)

- config.go
- tracker/client.go
- tracker/http/client.go
- tracker/tracker.go
- tracker/udp/conn-client.go
- tracker_scraper.go
I have had this branch lying around for a while, but decided to pick it back up, make it work with the latest master, and offer it as a PR.
Currently, this library has the ability to configure an HTTPProxy for HTTP tracker announcements. This is useful for a simple proxy, but it is somewhat limited if you want to do anything more advanced. Likewise, there is currently no way to proxy UDP tracker announcements.
This PR introduces two new configuration properties for `TrackerDialContext` and `TrackerListenPacket`. When they are defined they will take precedence over the default `http.Transport` options and `net.ListenPacket`.
Typically these would not be required since most people probably use a VPN at a lower level to prevent IP leaks, but these changes allow you to, for example, route all …
> Add ability to set DialContext/ListenPacket for tracker announcements

- cmd/torrent/metainfo.go
I just thought it would be neat.
Example usage:
```
$ torrent metainfo https://archive.org/download/night_of_the_living_dead/night_of_the_living_dead_archive.torrent magnet
magnet:?xt=urn:btih:bba0e98f114a1414eb808bdd2ce86e852afefdc2&dn=night_of_the_living_dead&tr=http%3A%2F%2Fbt1.archive.org%3A6969%2Fannounce&tr=http%3A%2F%2Fbt2.archive.org%3A6969%2Fannounce&ws=http%3A%2F%2Farchive.org%2Fdownload%2F&ws=http%3A%2F%2Fia600301.us.archive.org%2F22%2Fitems&ws=http%3A%2F%2Fia700301.us.archive.org%2F22%2Fitems
```
> Retrive file via HTTP URL in `metainfo.go`

- client.go
- config.go
- tracker/http/http.go
- tracker/tracker.go
- tracker_scraper.go
Exposes a method in `torrent.ClientConfig` to define a function that modifies the HTTP request. The method is called right before sending the request.
This could be used, for example, to add authentication headers to the request, which could be used to grant permission to a private tracker.
This addresses #784.
> Modify HTTP request before sending

- client.go
- config.go
- webtorrent/tracker-client.go
- wstracker.go
Expose a `WebtorrentTrackerHttpHeader` field in Client.config to let users define a function that returns an `http.Header` to be used in `Dialer.Dial()` when establishing a connection. Useful for adding authentication headers when using a private tracker, for example.
Addresses #784.
> Add customer headers when dialling WS connection to tracker

- storage/file-piece.go
If the file has never been downloaded, complete will naturally be false. It's
not necessary to then set it false again unless it was actually claimed to be
true in the first place.
In my tests, using the boltdb completion thingy with fsync turned *on*, this
reduced the cold start for big buck bunny from multiple seconds to just a few
ms.
> Remove unecessary completion "set"

- tracker/udp/conn-client.go
fix https://github.com/anacrolix/torrent/issues/845
Some traker servers do not follow the udp traker specification, and the response packet returned is larger than the defined udp buffer size. We need to handle the error instead of panic.
> fix: udp tracker panic

- fs/file_handle.go
I encountered a bug where when an application attempts to read "across" the EOF (i.e. try to read $x$ bytes starting at offset $y$ where $x+y > len(file)$ ). The application dies with "unexpected EOF".
This patch fixes the bug for me.
I suspect that the fuse library does not expect `Read` to return non-nil errors except when no data was able to be read, but wasn't able to get into that library enough to confirm.
> don't return error when trying to read past EOF

- torrent.go
We started seeing some rate of panics after we added periodic `(*Torrent).KnownSwarm()` call for debugging purposes.
It looks like in a few other places operations with t.conns are processed while  t.cl.rLock() is held, replicating the same behavior.
```
fatal error: concurrent map iteration and map write
goroutine 86949826 [running]:
github.com/anacrolix/torrent.(*Torrent).KnownSwarm(0xc00355a000)
go/src/github.com/anacrolix/torrent/torrent.go:248 +0x17d
...
```
> torrent.KnownSwarm: keep client lock when iterating over connections

- request-strategy/order.go
In profiles I collected correctness check https://github.com/anacrolix/torrent/blob/c73c99b372114204b3e62ab7fe7103b2477c7dee/request-strategy/order.go#L60-L66 takes up to 10% cpu time. Would it make sense to remove it from runtime and add a unit-test for that instead (if not already)?
additional discussion is in https://github.com/anacrolix/torrent/issues/897#issuecomment-1933596287
> GetRequestablePieces: remove runtime correctness check

- cmd/magnet-metainfo/main.go
- cmd/torrent/metainfo.go
- cmd/torrent/serve.go
- fs/torrentfs.go
- fs/torrentfs_test.go
- internal/cmd/issue-908/main.go
- internal/testutil/spec.go
- metainfo/info.go
- metainfo/metainfo_test.go
- spec.go
- storage/file.go
- storage/mmap.go
- webseed/request.go
running on macOS sonoma 14.4 with M2 pro 
I found some magnet with invalid utf8 name fail to download with this library. but meanwhile qbitorrent handle it well.
Maybe we should use `BestName` function in metainfo.Info and `BestPath` function in metainfo.FileInfo which may return 
human readable name in utf8 to successfully download this kind torrent.
before this patch invalid torrent will produce error message like this.
```shell
(base) ➜  Downloads torrent download 'magnet:?xt=urn:btih:0a5e2cbebf846baffd106bc01855bec11f6bd4e9'
361µs: getting torrent info for "infohash:0a5e2cbebf846baffd106bc01855bec11f6bd4e9"
9.145690083s: downloading "仙剑奇侠传三1080P": 0 B/72 GB, 0/4262 pieces completed (0 partial): 0 B/s
...
45.145761083s: downloading "仙剑奇侠传三1080P": 0 B/72 GB, 0/4262 pieces completed (0 …
```
> fix: can not download invalid utf8 named torrent

- client.go
- config.go
- go.sum
- webtorrent/tracker-client.go
- webtorrent/transport.go
- wstracker.go
Support passing ICE servers of type `[]webrtc.ICEServer` to the client config. This effectively enables the use of TURN servers when NAT traversal is needed. TURN servers normally require authentication, and the current implementation doesn't allow for that in the client config.
Fixes #903.
> Support ICE servers auth

- client.go
Remove code repetition when initialising `Client.websocketTrackers`.
> Tidy up client ICEServers

- webseed/client.go
This fix simplifies the go routine profile for http calls.
Instead of routine->channel-routine called one after the other (which is effectively synchronous the code executes in a single go routine.
This is to help elevate this go http related issue - which causes the torrent to panic:
```
panic: net/http: internal error: connCount underflow
goroutine 1030540 [running]:
net/http.(*Transport).decConnsPerHost(0xc0008dc9a0, {{0x0, 0x0}, {0xc00afd8980, 0x5}, {0xc0274e0360, 0x2f}, 0x0})
net/http/transport.go:1511 +0x405
net/http.(*Transport).roundTrip(0xc0008dc9a0, 0xc0039eb9e0)
net/http/transport.go:618 +0x876
net/http.(*Transport).RoundTrip(...)
net/http/roundtrip.go:17
github.com/ledgerwatch/erigon-lib/downloader.(*requestHandler).RoundTrip(0xc0008dc9a0, 0xc0039eb9e0) …
```
> Webseed Client - Close body in same go routine as request

- peer-conn-msg-writer.go
- peer-conn-msg-writer_test.go
- peer_protocol/msg.go
- requesting.go
This commit replaces the use of an intermediate buffer in the message serialization process with a direct write-to-buffer approach. The original implementation used MustMarshalBinary() which involved an extra memory copy to an intermediate buffer before writing to the final writeBuffer, leading to high memory consumption for large messages. The new WriteTo function writes message data directly to the writeBuffer, significantly reducing memory overhead and CPU time spent on garbage collection.
> Optimize memory usage by avoiding intermediate buffer in message serialization

- storage/file.go
I did it for MMAP: https://github.com/anacrolix/torrent/pull/755 , adding same thing for   `fileTorrentImpl`
> Add `fileTorrentImpl.Flush()` method

- portfwd.go
Accroding to https://github.com/anacrolix/torrent/pull/942#issuecomment-2131309178 , it no problem with go 1.22 or above, but we can still consider fixing it to improve compatibility with old go versions.
> fix: upnp clear loop trap

- peer_protocol/msg.go
- peerconn.go
- piece.go
This PR implemented serialization of Hashes and HashReject messages, and the logic of responding to HashRequest. Note that some code relevant to `Piece` is changed and should be reviewed.
> Basic support for responding to HashRequest

- torrent.go
- webtorrent/peer-conn-stats.go
- webtorrent/peer-conn-stats_js.go
- webtorrent/tracker-client.go
- webtorrent/transport.go
I revisited the work on #803 and improved on it. By saving a pointer to the open peer connections, we get stats more reliably. Stats now also work when seeding.
A note on the `Pion/webrtc` version. While some stats are available in the current latest version (`v3`), the project greatly improved on them in `v4`, currently in beta. I'd recommend upgrading to `v4` as soon as it's convenient when it gets out of beta.
> Expose WebRTC peerconn stats
