- cmd/torrent/main.go
> add cli flag to disable DHT

- metainfo/metainfo.go
Add Announce when AnnounceList is nil
> Add Announce when AnnounceList is nil

- cmd/torrentfs/main.go
- util/dirwatch/dirwatch.go
> dirwatch: fix panic when attemting to copy func into [20]byte

- cmd/torrent/main.go
Pass `seed` option value to Config for cmd/torrent
> Pass seed option to Config for cmd/torrent

- client_test.go
Warning: this unit test freezes. It does not properly bail out upon failure.
> Add a test case for #114

- cmd/torrent/main.go
Sometimes it's really usefull to do not download
torrent file locally but simply pass HTTP link
this patch adds such ability.
Signed-off-by: Igor Shishkin <me@teran.ru>
> Trivial HTTP support for adding torrent files by

- storage/boltPieceCompletion.go
- storage/boltpc_test.go
- storage/completion.go
- storage/completion_piece_map.go
- storage/file.go
- storage/mmap.go
In my environment, store the pieces completion information in memory is enough, so I need a method to create file storage and mmap storage with compeltion type.
> make completion configurable

- torrent.go
For #183. Please check `TODO`s before/after merging.
> added the initial version of the (t *Torrent) KnownSwarm() function

- README.md
I having been using your project for downloading torrent on my server for a couple of weeks now and it works very well. Thanks for your contribution! I used to use a simple HTTP file server to retrieve the downloaded files to my computer. As I used this cumbersome approach heavily on a daily basis, I began to implement a tool to download torrent efficiently just by running a local command with the magnet link which sends torrent download request to the server. You may find my current working prototype sloppy but please check out my project.
> Update "Other public projects using torrent" section on README.md

- config.go
- torrent.go
Hello @anacrolix ,
As discussed, a more aggressive upload to match the default behaviour from libtorrent.
You suggested making it the default behaviour, so I've included a config option to turn it off.
Regards,
iamacarpet
> Aggressive Upload

- storage/file.go
> Fix file permissions

- cmd/torrent/main.go
As suggested in #268, a small PR to terminate the `torrent` process while downloading.
As far as cleanup goes, performing a `client.Close` does everything needed. The method is goroutine-safe and the current code will no longer block on `client.WaitAll()` but proceed to `log.Fatal("y u no complete torrents?!")` which sounds reasonable to me.
Partially downloaded files are left as they are.
> cmd/torrent: Listen to termination signals

- bep40.go
- client.go
- connection.go
- connection_test.go
- ipport.go
- torrent.go
Don't assume the net.Conn has the correct values.
> Store network and remote address per connection

- cmd/torrent-create/main.go
Flags for setting Comment and CreatedBy fields and starting with empty AnnounceList
> Adds more flags to torrent-create

- tracker/peer.go
> check if peer id exists

- README.md
[ANT Downloader](https://github.com/anatasluo/ant) is a bittorrent client developed by golang, angular and electron. It has integrated many downsteam projects from anacrolix/torrent like goTorrent and Go Peerflix and some other public torrent services like [itorrents](https://itorrents.org/), [trackerslist](https://github.com/ngosang/trackerslist). It is a client for all platforms since golang and electron can be built in all platforms, mainly for linux since I think utorrent is not so beautiful ：D. Hope you like it.
> add one downstream project

- client.go
- config.go
this pr add OnQuery hook when create a new torrent client.
> Add OnQuery hook in init torrent client.

- file.go
Had to refactor this method as it was not working properly... (my bad)
This one should now work as expected.
> Fix bytesLeft for files

- cmd/torrent/main.go
> fix if statement in `cmd/torrent/main.go`

- client.go
- socket.go
disable listeners if proxy is configured
https://github.com/anacrolix/torrent/issues/359
> disable listeners if proxy is configured

- Peer.go
- bep40_test.go
- client.go
- connection_test.go
> fixes various vet errors

- piece.go
We had a bunch of back and forth about this over email, and this is a method I have been using in my fork now for a few months without any issues. It allows you to use a completely in memory storage implementation (or remove pieces stored in bolt db, for example), and make sure that everything remains in sync with the torrent client after evictions occur.
> Add Piece.UpdateCompletion() method

- peerconn.go
- torrent.go
Provides for ability to mark specific torrents as "don't upload".
> Add per-torrent ability to disable uploading

- .gitignore
- README.md
Change reference on PkgGoDev in README.md
> Fix PkgGoDev reference in README

- pex.go
As pointed out by @yarikk  https://github.com/anacrolix/torrent/commit/c1d189ed31af99cbf6f10d9ffdc2cc4e19a73b91#r43920706
> Fix initial pex message regression

- mmap_span/mmap_span.go
> Fix excessive logging from mmap-backed storage (anacrolix/torrent#436)

- pex.go
- pex_test.go
This requests pull of three commits:
* add TestPexInitialNoCutoff to catch regressions like anacrolix/torrent#433
* simplify `pexMsgFactory` to make better use of surrounding types
* optimise generation of the initial PEX
The latter deserves to be covered in greater detail.
The optimisation comes from the observation that every subsequent PEX message has to scan over the same bunch of events plus a small number of events on top of that. Included are benchmarks runnable with `go test -bench`.
Below are the benchmark results, and a plot showing the values of the last column along with the trend lines:
* before:
```
BenchmarkPexInitial4-8     	  102764	     11319 ns/op
BenchmarkPexInitial50-8    	    2024	    500112 ns/op
BenchmarkPexInitial100-8   	     656	   1851580 ns/op …
```
> optimise generation of the initial PEX

- pex.go
Turns out, storing the PEX message entries in maps for later extraction at message generation stage is very expensive. If we prepare the lists without storing in maps we gain a huge win for the initial message. Here are the new benchmarks:
```
BenchmarkPexInitial4-8     	  217302	      5089 ns/op
BenchmarkPexInitial50-8    	   24865	     48012 ns/op
BenchmarkPexInitial100-8   	   11413	     90340 ns/op
BenchmarkPexInitial200-8   	    6747	    189316 ns/op
BenchmarkPexInitial400-8   	    2803	    438807 ns/op
```
Comparing these against the "after" benchmark of #435, we may observe significant improvement:
Accounting for reconnections may become slower but those, at later stages, come on top of the log processed earlier, amortising the cost.
> Optimise PEX by avoiding intermediate storage

- webtorrent/tracker_client.go
OpenWebTorrent disconnects clients after two minutes of inactivity. In a scenario where an
announce occurs and no other activity occurs for the (default) 120-second idle timer, the
websocket will be torn down by OpenWebTorrent. This in turn causes the tracker client to wait one
minute, reconnect, and reannounce its peers.
This patch sends a websocket.PingMessage every 60 seconds to maintain the connection.
Relates to #416
> Ping websocket to ensure connection remains online.

- webtorrent/tracker_client.go
Fixes the panic introduced by #455
See also: https://github.com/anacrolix/torrent/issues/416
> Fix panic on Ping/WriteMessage for webtorrent

- .deepsource.toml
- fs/torrentfs.go
- mse/mse.go
- mse/mse_test.go
- webtorrent/tracker_client.go
Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/torrent/issues/). This PR fixes a few of them.
- Removed empty default in select
- Removed unnecessary use of slice
- Fixed check for empty string
- Added .deepsource.toml
> fix: code quality issues

- cmd/torrent/main.go
- storage/file.go
https://github.com/anacrolix/torrent/issues/485#issue-881221086
> Allows one to use Custom PieceCompletion

- config.go
.. Or go get https://github.com/anacrolix/missinggo/pull/20
> package expect fix

- config.go
- go.mod
- go.sum
https://github.com/anacrolix/missinggo/pull/20
> missinggo go.mod fix

- go.mod
- go.sum
Mainly to support this: https://github.com/anacrolix/dht/pull/46
> [gomod] Update anacrolix/dht and run 'go mod tidy'

- peer_protocol/handshake.go
Nothing wrong with missinggo.CopyExact -- but fewer dependencies is better IMO.  Also changed String() to use a consistent receiver name -- not a big deal.
> Drop xerrors and reflection dependency

- client.go
A similar case of `haveDhtServer`
> Simplify dhtPort()

- client.go
Additional tweaks to context passing and looping
> useTorrentSources: fix http request resource leak

- file.go
Seems worthwhile when setting/getting priorities for many files
> Inlineable methods to access File piecePriority

- client.go
`eachListener` might be confusing since using it doesn't actually loop over each listener. A perfectly simple C-style for loop is all that's needed. Can't go wrong with C -- Go can actually inline these, as dumb as it is sometimes.
Using `eachListener` inside `findListener` makes things confusing as well, so I fixed that. I didn't change `eachListener` as I'm not sure what to do with it.
> Fix usages of eachListener() and make inlineable

- bencode/misc.go
Revamped https://github.com/anacrolix/torrent/pull/587
> Cheaper byte to string conversion

- listen.go
Honestly don't even know why I bothered with this -- it's basically inconsequential. It's faster nonetheless though lol
> Optimize `LoopbackListenHost()`

- peerconn.go
Continuing my crusade to clean up stray logs!
> Use PeerConn logger instead of default logger

- torrent.go
> Use Torrent logger instead of default logger

- peerconn.go
This function is very useful and could be accessible to library users.
> Expose `Peer.DownloadRate`

- .github/workflows/codeql-analysis.yml
Updates the outdated codeql analysis actions to v2
> Update codeql analysis to v2

- pex.go
- pexconn.go
This is what I'm thinking if https://github.com/anacrolix/torrent/discussions/836#discussioncomment-5984103 is correct?
> Reintroduce torrent-wide PEX throttling

- file.go
- file_test.go
- tracker/udp/conn-client.go
fixed https://github.com/anacrolix/torrent/issues/851.
> fix: torrent file real time completed bytes

- metainfo/file-tree.go
- metainfo/info.go
Implements bencode.Marshaler for FileTree
Omit Pieces field in torrent info if empty
> Basic support for serializing v2 torrent file

- doc.go
Fixing docs to note that WebSeed is supported.
> WebSeed seems supported
